name: decoy
description: A new Flutter project.

version: 1.3.0

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1 
  isar_flutter_libs: ^3.1.0+1
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  provider: ^6.1.1
  pedometer: ^4.1.0
  permission_handler: ^12.0.0
  intl: ^0.18.0
  flutter_local_notifications: ^17.2.3
  fl_chart: ^0.55.2
  timezone: ^0.9.1
  time_machine: ^0.9.16
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/group_one.png
    - assets/images/add_friend.png
    - assets/images/back.png
    - assets/images/change_password.png
    - assets/images/exit_from_account.png
    - assets/images/friends.png
    - assets/images/personal_info.png
    - assets/images/profile.png
    - assets/images/walk_60.png
    - assets/images/profile_60.png
    - assets/images/water_60.png
    - assets/images/steps_60.png
    - assets/images/chat_60.png
    - assets/fonts/static/Inter_18pt-Regular.ttf
    - assets/fonts/static/Inter_18pt-Medium.ttf
    - assets/fonts/static/Inter_18pt-SemiBold.ttf
    - assets/fonts/static/Inter_18pt-Bold.ttf
    - assets/fonts/static/Inter_18pt-Black.ttf
    

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Inter_18pt-Black.ttf
          weight: 900

environment:
  sdk: ^3.7.2